version: '3.4'

services:
  restfulqr.api:
    image: ${DOCKER_REGISTRY-}restfulqrapi
    build:
      context: .
      dockerfile: RestfulQr.Api/Dockerfile

  restfulqr.db:
    image: postgres
    restart: unless-stopped

  restfulqr.caching:
    image: redis
    restart: unless-stopped