using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestfulQr.Domain
{
    /// <summary>
    /// Represents an api key that is required by users to create and retrieve qr codes
    /// </summary>
    public class ApiKey
    {
        /// <summary>
        /// The unique ID of the API key
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// A short number that can be used to uniquely identify an api key. Any images
        /// generated by the api key will be stored under a folder with a name matching
        /// this value.
        /// </summary>
        public long LocationId { get; set; }

        /// <summary>
        /// The date the api key was created
        /// </summary>
        public DateTime Created { get; set; }

        /// <summary>
        /// The last datetime that the api key was successfully used
        /// </summary>
        public DateTime LastUsed { get; set; }
    }
}